### ISSUE TITLE
Starfield extraction not working - Solution Included

### ISSUE THREAD

**Issue by romkslrqusz** [Z1ni/XGP-save-extractor#12]
I ran into problems trying to convert my Starfield saves. It seemed as though it was trying to find a folder for Hades (I no longer have it installed), couldn't, and halted the script there instead of moving on. Starfield never even got detected.

**Full output:**

```
Xbox Game Pass for PC savefile extractor
========================================
Installed supported games:
- Hades
Traceback (most recent call last):
  File "main.py", line 275, in <module>
    main()
  File "main.py", line 251, in main
    store_pkg_name, containers = read_containers(supported_xgp_apps[name])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 50, in read_containers
    dirs = [d for d in os.listdir(wgs_dir) if d != "t"]
                       ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\romks\\AppData\\Local\\Packages\\SupergiantGamesLLC.Hades_q53c1yqmx7pha\\SystemAppData\\wgs'
[21468] Failed to execute script 'main' due to unhandled exception!
```

**I edited main.py so that it would only look for Starfield:**

```
import os
import struct
import sys
import tempfile
import uuid
import zipfile
from datetime import datetime
from pathlib import Path, PurePath

# Xbox Game Pass for PC savefile extractor

# Running: Just run the script with Python 3 to create ZIP files that contain the save files

# Thanks to @snoozbuster for figuring out the container format at https://github.com/goatfungus/NMSSaveEditor/issues/306

# List of supported Game Pass games and their UWP package names
supported_xgp_apps = {
    "Starfield": "BethesdaSoftworks.ProjectGold_3275kfvn8vcwc"
}


def discover_games():
    found_games = []
    for game_name, pkg_name in supported_xgp_apps.items():
        pkg_path = os.path.expandvars(f"%LOCALAPPDATA%\\Packages\\{pkg_name}")
        if os.path.exists(pkg_path):
            found_games.append(game_name)
    return found_games


def read_utf16_str(f, str_len=None):
    if not str_len:
        str_len = struct.unpack("<i", f.read(4))[0]
    return f.read(str_len * 2).decode("utf-16").rstrip("\0")


def read_containers(pkg_name):
    # Find container dir
    wgs_dir = os.path.expandvars(f"%LOCALAPPDATA%\\Packages\\{pkg_name}\\SystemAppData\\wgs")
    # Get the correct user directory
    dirs = [d for d in os.listdir(wgs_dir) if d != "t"]
    dir_count = len(dirs)
    if dir_count != 1:
        raise Exception(f"Expected one user directory in wgs directory, found {dir_count}")

    containers_dir = os.path.join(wgs_dir, dirs[0])
    containers_idx_path = os.path.join(containers_dir, "containers.index")

    containers = []

    # Read the index file
    with open(containers_idx_path, "rb") as f:
        # Unknown
        f.read(4)

        container_count = struct.unpack("<i", f.read(4))[0]

        # Unknown
        f.read(4)

        store_pkg_name = read_utf16_str(f).split("!Game")[0].split("!Retail")[0].split("!AppChorusShipping")[0].split("!App")[0]

        # Unknown
        f.read(12)
        read_utf16_str(f)

        # Unknown
        f.read(8)

        for _ in range(container_count):
            # Container name
            container_name = read_utf16_str(f)
            # Duplicate of the file name
            read_utf16_str(f)
            # Unknown quoted hex number
            read_utf16_str(f)
            # Container number
            container_num = struct.unpack("B", f.read(1))[0]
            # Unknown
            f.read(4)
            # Read container (folder) GUID
            container_guid = uuid.UUID(bytes_le=f.read(16))
            # Unknown
            f.read(24)

            files = []

            # Read the container file in the container directory
            container_path = os.path.join(containers_dir, container_guid.hex.upper())
            with open(os.path.join(container_path, f"container.{container_num}"), "rb") as cf:
                # Unknown (always 04 00 00 00 ?)
                cf.read(4)
                # Number of files in this container
                file_count = struct.unpack("<i", cf.read(4))[0]
                for _ in range(file_count):
                    # File name, 0x80 (128) bytes UTF-16 = 64 characters
                    file_name = read_utf16_str(cf, 64)
                    # Read file GUID
                    file_guid = uuid.UUID(bytes_le=cf.read(16))
                    # Ignore the copy of the GUID
                    cf.read(16)

                    files.append({
                        "name": file_name,
                        # "guid": file_guid,
                        "path": os.path.join(container_path, file_guid.hex.upper())
                    })

            containers.append({
                "name": container_name,
                "number": container_num,
                # "guid": container_guid,
                "files": files
            })

    return (store_pkg_name, containers)


def get_save_paths(store_pkg_name, containers, temp_dir):
    save_meta = []

    if store_pkg_name in [supported_xgp_apps["Starfield"]]:
        # Starfield
        # The Steam version uses SFS ("Starfield save"?) files, whereas the Store version splits the SFS files into multiple files inside the containers.
        # One container is one save.
        # It seems that the "BETHESDAPFH" file is a header which is padded to the next 16 byte boundary with the string "padding\0", where \0 is NUL.
        # The other files ("PnP", where n is a number starting from 0) are then concatenated into the SFS file, also with padding.

        temp_folder = Path(temp_dir.name) / "Starfield"
        temp_folder.mkdir()

        pad_str = "padding\0" * 2

        for container in containers:
            path = PurePath(container["name"])
            # There can be other files than saves, e.g. files under "Settings/" path. Skip those.
            if path.parent.name != "Saves":
                continue
            # Strip out the parent folder name
            sfs_name = path.name
            # Arrange the files: header as index 0, P0P as 1, P1P as 2, etc.
            parts = {}
            for file in container["files"]:
                if file["name"] == "BETHESDAPFH":
                    parts[0] = file["path"]
                else:
                    idx = int(file["name"].strip("P")) + 1
                    parts[idx] = file["path"]
            # Construct the SFS file
            sfs_path = temp_folder / sfs_name
            with sfs_path.open("wb") as sfs_f:
                for idx, part_path in sorted(parts.items(), key=lambda t: t[0]):
                    with open(part_path, "rb") as part_f:
                        data = part_f.read()
                    size = sfs_f.write(data)
                    pad = 16 - (size % 16)
                    if pad != 16:
                        sfs_f.write(pad_str[:pad].encode("ascii"))

            save_meta.append((sfs_name, sfs_path))

    else:
        raise Exception("Unsupported XGP app \"%s\"" % store_pkg_name)

    return save_meta


def main():
    print("Xbox Game Pass for PC savefile extractor")
    print("========================================")

    # Create tempfile directory
    # Control save files need this, as we need to create files that do not exist in the XGP save data
    temp_dir = tempfile.TemporaryDirectory(ignore_cleanup_errors=True)

    # Discover supported games
    found_games = discover_games()

    if len(found_games) == 0:
        print("No supported games installed")
        sys.exit(1)

    print("Installed supported games:")
    for name in found_games:
        print("- %s" % name)

        store_pkg_name, containers = read_containers(supported_xgp_apps[name])

        # Get save file paths
        save_paths = get_save_paths(store_pkg_name, containers, temp_dir)
        print("  Save files:")
        for file_name, _ in save_paths:
            print(f"  - {file_name}")

        # Create a ZIP file
        formatted_game_name = name.replace(" ", "_").replace(":", "_").replace("'", "").lower()
        timestamp = datetime.now().strftime("%Y-%m-%d_%H_%M_%S")
        zip_name = "%s_%s.zip" % (formatted_game_name, timestamp)
        with zipfile.ZipFile(zip_name, "x") as save_zip:
            for file_name, file_path in save_paths:
                save_zip.write(file_path, arcname=file_name)

        print()
        print("  Save files written to \"%s\"" % zip_name)
        print()

    temp_dir.cleanup()


if __name__ == "__main__":
    main()
```

I am no2 happily playing again :]
Thank you so much @Z1ni !

**Comment by Z1ni** [comment]
Thanks for the report, I'll add some error handling so missing games get skipped.

**Comment by Maxavelli** [comment]
error handling adding didn't work it seems as your latest build on sept 14 just gives an error which says it can't find save file auto...somethingsomething.sfs which is weird. Isn't that the format it should save the files as? Anyhoo appreciate your work and I'll just try what done by the person above and hopefully that will work. Peace!

**Comment by Z1ni** [comment]
The Xbox save data can contain (at least for Starfield) the same file more than once. One version of the file might be missing, but another isn't. That's why the newest version warns you about the missing file, but notes that the extracted saves might still work. The previous version would just crash and not produce any files in that case.
