### ISSUE TITLE
Support for [Palworld]

### ISSUE THREAD

**Issue by NewComerFrom** [Z1ni/XGP-save-extractor#128]

**Comment by NewComerFrom** [comment]
i get error it worked once then i edit with save with save editor then imported and now i cant extract another save and now i get this error

Xbox Game Pass for PC savefile extractor
========================================
Installed supported games:
- Palworld
  Failed to extract saves:
Traceback (most recent call last):
  File "\\VBoxSvr\Share\main.py", line 422, in main
  File "\\VBoxSvr\Share\main.py", line 382, in get_save_paths
IndexError: list index out of range


Press enter to quit
