### ISSUE TITLE
Palworld XGP Save Extractor Error

### ISSUE THREAD

**Issue by NewComerFrom** [Z1ni/XGP-save-extractor#129]
i get a error it worked once then i edit with save with save editor then imported and now i cant extract another save and now i get this error
Xbox Game Pass for PC savefile extractor

Installed supported games:

    Palworld
    Failed to extract saves:
    Traceback (most recent call last):
    File "\VBoxSvr\Share\main.py", line 422, in main
    File "\VBoxSvr\Share\main.py", line 382, in get_save_paths
    IndexError: list index out of range

Press enter to quit

**Comment by NewComerFrom** [comment]
i have latest exe and i even tried doing the source code way i am now trying reinstall game and also im gonna delete all save data from everywhere on xbox

**Comment by NewComerFrom** [comment]
> i have latest exe and i even tried doing the source code way i am now trying reinstall game and also im gonna delete all save data from everywhere on xbox

Yes doing that has worked if anyone else has received this error thats the fix
