### ISSUE TITLE
Starfield Failed to extract Saves

### ISSUE THREAD

**Issue by Oninfinity5** [Z1ni/XGP-save-extractor#16]
When I run the extractor it gives me this message 

Installed supported games:
- Starfield
  Failed to extract saves:
Traceback (most recent call last):
  File "C:\MyScripts\XGP-save-extractor-main\main.py", line 263, in main
    save_paths = get_save_paths(store_pkg_name, containers, temp_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyScripts\XGP-save-extractor-main\main.py", line 230, in get_save_paths
    raise Exception("Unsupported XGP app \"%s\"" % store_pkg_name)
Exception: Unsupported XGP app "<<PROCESS_12240>>"

I have the xbox app and starfield is installed through it, so I have no idea why it says that

**Comment by Oninfinity5** [comment]
Nevermind I figured it out just had to move the game to the C drive, not sure how to delete the post though
