### ISSUE TITLE
Failed to create save game error and how I'm trying to "fix" it.

### ISSUE THREAD

**Issue by EuphoniousNonsense** [Z1ni/XGP-save-extractor#18]
I posted this to reddit as well but I think this is a better place to maybe get help.  My goal here is just simply recover my last save file, which does still load fine and works without issue but i cannot save due to the error/bug, and then convert to steam friendly save file so I can stop using the Xbox Game Pass version and use the steam version instead.

**_REDDIT POST 1_**

Been fighting this after getting to lvl 17 last night. When i booted game today getting this error. Tried everything listed here. I decided the best course of action was the converter from xbox game pass to steam and I would just buy the game there HOWEVER when I try to run the python script i get an error. The strange part is if I revert this file
C:\Users\*myusername*\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\00090000039FB06A_0000000000000000000000007BF72399\containers.index
back to the default that I saved a backup of before playing (thanks bethesda, this is a trait your games created in me) it will run just the script fine not when using the file my game has created over the course of playing it. I cannot code nor do I have the patience to teach myself it to figure this issue out. Anyone got any ideas?
Here is the error
C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06>python main.py

Xbox Game Pass for PC savefile extractor

========================================

Installed supported games:

- Starfield

Failed to extract saves:

Traceback (most recent call last):

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 255, in main

read_result = read_containers(supported_xgp_apps[name])

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 102, in read_containers

with open(os.path.join(container_path, f"container.{container_num}"), "rb") as cf:

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*myusername*\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\00090000039FB06A_0000000000000000000000007BF72399\\6A105BD4D7F54CFB819A80B6C046C7A5\\container.2'
PLEASE NOTE - *myusername* is not my actual username just a placeholder. * are invalid for file names.

**_REDDIT POST REPLY 1_**

Tried recreating the folders it was looking for in the script with a container.2 file in each but we get to the end and now i am getting this error I cannot seem to solve.
C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06>python main.py

Xbox Game Pass for PC savefile extractor

========================================

Installed supported games:

- Starfield

Failed to extract saves:

Traceback (most recent call last):

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 263, in main

save_paths = get_save_paths(store_pkg_name, containers, temp_dir)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 220, in get_save_paths

with open(part_path, "rb") as part_f:

^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*myusername*\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\00090000039FB06A_0000000000000000000000007BF72399\\6A105BD4D7F54CFB819A80B6C046C7A5\\600D23C8F23D4EBBA3D9DC95152DAE2C'

**_REDDIT POST REPLY 2_**

Created a copy of container.2 and renamed it to 600D23C8F23D4EBBA3D9DC95152DAE2C and then deleted the file extension. This actually worked to move to next file and got me past that error.  I did the same to the next files it listed however ended up in a loop.  Stuck back at as of right now.

 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*myusername*\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\00090000039FB06A_0000000000000000000000007BF72399\\6A105BD4D7F54CFB819A80B6C046C7A5\\600D23C8F23D4EBBA3D9DC95152DAE2C

**Comment by EuphoniousNonsense** [comment]
For Reference here is the reddit post.

https://www.reddit.com/r/Starfield/comments/167b50s/failed_to_create_save_game/

**Comment by Fitzpaa** [comment]
You shouldn’t be changing and file names. 

Ensure that your gamepass save is on your C drive and that you have Python version 3.1 or greater installed.  
Download the xgp-save-extractor.exe from https://github.com/Z1ni/XGP-save-extractor/releases

**Comment by Fitzpaa** [comment]
Whatever directory your xgp-save-extractor.exe is in will get a starfield zip file with all your saves in steam format. Just grab the save you want there and place it in your C:\Users\myusername\documents\my games\starfield\Saves

And run your game and load you save file

**Comment by EuphoniousNonsense** [comment]
My save files are located
in C:\Users\*myusername*\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\00090000039FB06A_0000000000000000000000007BF72399
 as there is no save folder in C:\Users\*myusername*\Documents\My
Games\Starfield yet I can still, to this second, load my most recent save.
I did what you posted prior to making my previous post.  If it wasnt
obvious I was simply trying to move past the errors in hopes the last save
file would convert and I could just move on with my life.   As you can tell
that was not  the case.  I/WE shouldn't be having to do any of this shit at
all but hey it's Bethesda......  Right??

**Comment by EuphoniousNonsense** [comment]
I tried it the way you mentioned again and end up with this error.

C:\Users\*myusername*\Downloads>xgp-save-extractor.exe
Xbox Game Pass for PC savefile extractor
========================================
Installed supported games:
- Starfield
  Failed to extract saves:
Traceback (most recent call last):
  File "main.py", line 255, in main
  File "main.py", line 102, in read_containers
FileNotFoundError: [Errno 2] No such file or directory:
'C:\\Users\\*myusername\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\00090000039FB06A_0000000000000000000000007BF72399\\6A105BD4D7F54CFB819A80B6C046C7A5\\container.2'

**Comment by EuphoniousNonsense** [comment]
I have a feeling its trying to pull files that somehow got corrupted.  I only want to do the most recent save.

**Comment by willrun4fun** [comment]
I'm getting the same error.  I am also emailing my zipped folder.

**Comment by wildermason** [comment]
I get the same error as well. I wonder if its either a corrupted save or a deleted save that hasn't synced properly or something. Checked the folder it mentions and it indeed empty. 

I have 708 folders in the `C:\Users\<USERNAME>\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\000900000643B5A0_0000000000000000000000007BF72399` directory, and checking a few I notice they are empty, but no idea just how many (seems like there are more empty ones than with files inside).

All I care about is getting the most recent save of mine exported/backed up. Is there any way to just target specifically 1 save (maybe just get the most recent) or skip any that are empty?

**Comment by willrun4fun** [comment]
The latest update fixed it for me.  This started happening after I deleted a lot of my old saves from the in-game UI.

**Comment by Z1ni** [comment]
I'm pretty sure that these issues are caused by in progress / interrupted Xbox cloud save syncing or too many saves.

The newest release outputs warning messages if files are missing, but you can still continue. In some cases the missing files are duplicated in the save data, so the extracted saves are complete, even though the script warns about missing files.

If you're still having this issue, please check out the [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-09-14) and reopen this issue if the error persists.
