### ISSUE TITLE
Need help for extracting palworld files

### ISSUE THREAD

**Issue by TimothyIbisate** [Z1ni/XGP-save-extractor#204]
- Palworld
  Failed to extract saves:
Traceback (most recent call last):
  File "main.py", line 514, in main
  File "main.py", line 395, in get_save_paths
IndexError: list index out of range
Always getting this message when trying to extract palworld files and I cant find a solution anywhere any help would be much appreciated. Thanks!

**Comment by JimMessenger** [comment]
Also have problem with XGP save extractor with Palworld.    On booting Steam version with transferred files from Gamepass get an error FailedInvalidLoginPlayerCharacter Handle.  Initial load screen has correct user name, level is correct, etc.   Others on the net are pointing at a .sav file carrying incorrect data.

**Comment by mczubaj** [comment]
Had problems with it too, this guide helped - https://www.reddit.com/r/Palworld/comments/1ho9gux/how_to_transfer_your_palworld_save_from_xbox_game/
