### ISSUE TITLE
Support for PalWorld

### ISSUE THREAD

**Issue by GustavoGFV** [Z1ni/XGP-save-extractor#211]
Hello there,
Been trying to export the XGP saves to my steam, using the XGP exe and later sending the level.sav to PalWorld SaveTools, to convert it into JSON, but it always says the sav is broken in someway on the code, the last error was 
Decompressing sav file
Traceback (most recent call last):
  File "C:\Users\===\Downloads\PalWorldSaveTools-main\PalWorldSaveTools-main\convert.py", line 136, in <module>
    main()
  File "C:\Users\===\Downloads\PalWorldSaveTools-main\PalWorldSaveTools-main\convert.py", line 56, in main
    convert_sav_to_json(
  File "C:\Users\===\Downloads\PalWorldSaveTools-main\PalWorldSaveTools-main\convert.py", line 87, in convert_sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
  File "C:\Users\===\Downloads\PalWorldSaveTools-main\PalWorldSaveTools-main\external_libs\palworld_save_tools\palsav.py", line 26, in decompress_sav_to_gvas
    raise Exception(
Exception: Not a compressed Palworld save, found b'CNK' instead of b'PlZ'

It seems to be a problem related to the XGP.exe because even when i tried other plataforms to convert it returns to be broken, it doesnt work if a just copy and paste the values on Steam saves, because when loaded the game just makes a new character and resets it all, just keeping the areas from the map that i went, but not the checkpoints.

**Comment by Natedogg409** [comment]
I'm having a similar issue i tried using this to transfer my save and it seems to work when i select the world it show my level 48 character but then makes me start a new character. i noticed that in my save file in steam it has a level.Sav file but in the file transferred from Xbox it has a folder named level with a file 01.sav inside. might have something to do with this?

**Comment by mczubaj** [comment]
Had problems with it too, this guide helped - https://www.reddit.com/r/Palworld/comments/1ho9gux/how_to_transfer_your_palworld_save_from_xbox_game/
